language: php

dist: trusty

php:
    - '7.3'

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $MONOFONY_CACHE_DIR

env:
    global:
        - APP_ENV=test
        - IS_DOCTRINE_ORM_SUPPORTED=true
        - DATABASE_URL=mysql://root@127.0.0.1:3306/monofony_%kernel.environment%?serverVersion=5.7
        - MONOFONY_CACHE_DIR=$HOME/.monofony-cache
        - MONOFONY_BUILD_DIR=etc/build
        - SYMFONY_ENDPOINT=https://flex.symfony.com/r/github.com/symfony/recipes-contrib/871

before_install:
    - nvm install 12
    - nvm use 12
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${MONOFONY_CACHE_DIR}"

install:
    - composer install --no-interaction --prefer-dist
    - export SYMFONY_ENDPOINT=
    - composer self-update --2
    - |
        composer remove \
            monofony/api-bundle \
            monofony/front-bundle \
            monofony/admin-bundle \
            monofony/core-bundle \
            monofony/fixtures-plugin \
            --no-update --no-scripts --no-plugins
    - |
        composer require \
            monofony/core-pack \
            monofony/api-pack \
            monofony/admin-pack \
            monofony/front-pack \
            symfony/dotenv:4.4.4 \
            symfony/flex:^1.9 \
            symfony/monolog-bundle:^3.1 \
            symfony/webpack-encore-bundle:^1.7 \
            --no-update --no-scripts --no-plugins
    - composer require --dev monofony/test-pack:^0.4 --no-update --no-scripts --no-plugins
    - rm config/packages/eight_points_guzzle.yaml
    - rm config/packages/sensio_framework_extra.yaml
    - rm config/packages/sonata_core.yaml

    - find . name="*.php" -type f -exec sed -i -e 's/Monofony\\Component\\Core\\Model\\User\\AdminUserInterface/Monofony\\Contracts\\Core\\Model\\User\\AdminUserInterface/g' {} \;
    - find . name="*.php" -type f -exec sed -i -e 's/Monofony\\Component\\Core\\Model\\User\\AdminAvatarInterface/Monofony\\Contracts\\Core\\Model\\User\\AdminAvatarInterface/g' {} \;
    - find . name="*.php" -type f -exec sed -i -e 's/Monofony\\Component\\Core\\Model\\Media\\FileInterface/Monofony\\Contracts\\Core\\Model\\Media\\FileInterface/g' {} \;
    - find . name="*.php" -type f -exec sed -i -e 's/Monofony\\Component\\Core\\Model\\User\\AppUserInterface/Monofony\\Contracts\\Core\\Model\\User\\AppUserInterface/g' {} \;
    - find . name="*.php" -type f -exec sed -i -e 's/Monofony\\Component\\Core\\Model\\Customer\\CustomerInterface/Monofony\\Contracts\\Core\\Model\\Customer\\CustomerInterface/g' {} \;
    - find . name="*.php" -type f -exec sed -i -e 's/Monofony\\Bundle\\AdminBundle\\Dashboard\\DashboardStatisticsProviderInterface/Monofony\\Contracts\\Admin\\Dashboard\\DashboardStatisticsProviderInterface/g' {} \;
    - find . name="*.php" -type f -exec sed -i -e 's/Monofony\\Bundle\\CoreBundle\\Tests\\Behat\\Service\\AdminSecurityServiceInterface/Monofony\\Bridge\\Behat\\Service\\AdminSecurityServiceInterface/g' {} \;
    - find . name="*.yaml" -type f -exec sed -i -e 's/Monofony\\Bundle\\CoreBundle\\Entity\\OAuth\\ClientManager/monofony.client_manager/g' {} \;
    - find . name="*.yaml" -type f -exec sed -i -e 's/vendor\/monofony\/core-bundle\/Resources\/config\/services_test.yaml/vendor\/monofony\/behat-bridge\/services_test.yaml/g' {} \;

    - sed -i -e 's/Doctrine\\Bundle\\FixturesBundle/\/\/ Doctrine\\Bundle\\FixturesBundle/g' config/bundles.php
    - sed -i -e 's/EightPoints\\Bundle\\GuzzleBundle/\/\/ EightPoints\\Bundle\\GuzzleBundle/g' config/bundles.php
    - sed -i -e 's/Monofony\\Bundle\\ApiBundle/\/\/ Monofony\\Bundle\\ApiBundle/g' config/bundles.php
    - sed -i -e 's/Monofony\\Plugin\\FixturesPlugin/\/\/ Monofony\\Plugin\\FixturesPlugin/g' config/bundles.php
    - sed -i -e 's/Monofony\\Bundle\\FrontBundle/\/\/ Monofony\\Bundle\\FrontBundle/g' config/bundles.php
    - sed -i -e 's/Sonata\\CoreBundle\\SonataCoreBundle/\/\/ Sonata\\CoreBundle\\SonataCoreBundle/g' config/bundles.php
    - sed -i -e 's/Sensio\\Bundle\\FrameworkExtraBundle/\/\/ Sensio\\Bundle\\FrameworkExtraBundle/g' config/bundles.php

    - composer update

    # Migrations

    - composer require symfony/dotenv symfony/validator symfony/monolog-bundle --no-scripts
    - composer remove monofony/api-bundle
    - composer remove monofony/front-bundle
    - composer remove monofony/admin-bundle
    - composer remove monofony/fixtures-plugin
    - composer remove monofony/core-bundle --no-update
    - composer require --dev monofony/test-pack:^0.4 -W
    - composer require monofony/core-pack:^0.4 monofony/core-pack:^0.4 monofony/api-pack:^0.4 -W

    - composer dump-env test
    - yarn install

before_script:
    - bin/console doctrine:database:create -vvv
    - APP_DEBUG=1 APP_ENV=dev bin/console cache:warmup -vvv # For PHPStan
    - bin/console doctrine:migration:migrate -n -vv
    - bin/console assets:install public -vvv
    - bin/console cache:warmup -vvv
    - yarn build

    # Configure display
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1680x1050x16
    - export DISPLAY=:99

    # Download Symfony CLI
    - |
        if [ ! -f $MONOFONY_CACHE_DIR/symfony ]; then
            wget https://get.symfony.com/cli/installer -O - | bash
            mv ~/.symfony/bin/symfony $MONOFONY_CACHE_DIR
        fi

    # Download and configure ChromeDriver
    - |
        if [ ! -f $MONOFONY_CACHE_DIR/chromedriver ] || [ "$($MONOFONY_CACHE_DIR/chromedriver --version | grep -c 2.34)" = "0" ]; then
            curl http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip > chromedriver.zip
            unzip chromedriver.zip
            chmod +x chromedriver
            mv chromedriver $MONOFONY_CACHE_DIR
        fi

    # Run ChromeDriver
    - $MONOFONY_CACHE_DIR/chromedriver > /dev/null 2>&1 &

    # Download and configure Selenium
    - |
        if [ ! -f $MONOFONY_CACHE_DIR/selenium.jar ] || [ "$(java -jar $MONOFONY_CACHE_DIR/selenium.jar --version | grep -c 3.4.0)" = "0" ]; then
            curl http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar > selenium.jar
            mv selenium.jar $MONOFONY_CACHE_DIR
        fi

    # Run Selenium
    - java -Dwebdriver.chrome.driver=$MONOFONY_CACHE_DIR/chromedriver -jar $MONOFONY_CACHE_DIR/selenium.jar > /dev/null 2>&1 &

    # Run webserver
    - $MONOFONY_CACHE_DIR/symfony server:ca:install
    - $MONOFONY_CACHE_DIR/symfony server:start --port=8080 --dir=public --force-php-discovery --daemon

script:
    - composer validate --strict
    - vendor/bin/security-checker security:check
    - bin/console doctrine:schema:validate -vvv
    - bin/console lint:twig templates
    - bin/console lint:yaml config --parse-tags
    - phpdbg -qrr vendor/bin/phpspec run --no-interaction -f dot
    - vendor/bin/phpstan analyse -c phpstan.neon -l 1 src
    - vendor/bin/psalm --show-info=false
    - vendor/bin/phpunit
    - bin/console app:install --no-interaction -vvv
    - bin/console sylius:fixtures:load default --no-interaction
    - vendor/bin/behat --strict -vvv --no-interaction -f progress || vendor/bin/behat --strict -vvv --no-interaction -f progress --rerun
    - (bin/console doctrine:migrations:migrate first --no-interaction && bin/console doctrine:migrations:migrate latest --no-interaction)

after_failure:
    - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "${MONOFONY_BUILD_DIR}/*.log"

notifications:
    email: false
